### ISSUE TITLE
Builds for macOS

### ISSUE THREAD

**Issue by jtalowell** [jtalowell/crackme#3]
The compiled release **does not** support macOS as of _0.0.3_.

I do not own any apple hardware to test on but I suspect that it should be possible to build for macOS without modifications to the source code.

- [x] Check whether or not the project can be built for macOS without significant source code modifications.
- [ ] Improve the release system such that we have Linux & macOS binaries available.

**Comment by CliffordSesel** [comment]
checked out the code on OSX 
built
appears to be working

**Comment by jtalowell** [comment]
@Tsoyuzhu has updated the wiki with instructions for setting up Vagrant and VirtualBox.

I have decided that supporting builds for different operating systems is not worth the effort. It is more sensible to focus on providing a consistent experience in Linux.
